### ISSUE TITLE
https://kernel360.github.io/ 에서 바로 블로그 연결

### ISSUE THREAD

**Issue by minsuklee** [Kernel360/blog#10]
https://kernel360.github.io/ 에 접속하면  404 에러가 나옵니다.
지금 블로그가 repo의 blog repo에 있기 때문인데요..

이미 논의가 되었는지 모르지만,

kernel360.github.io repo를 만들고 거기서 blog 로 forward를 하도록 만들면 접근성이 더 좋아질 것 같습니다.

그러다가 
kernel360.github.io에 블로그 말고 다른 것이 더 있다면 바꿔도 되고요.

**Comment by corazzon** [comment]
https://kernel360.github.io/  를 다른 용도로 사용할 수도 있을 거 같아서 의도적으로 blog 로 만들었는데요.
말씀해 주신 것처럼 https://kernel360.github.io/ 에서 https://kernel360.github.io/blog 로 포워딩 하는 것을 논의해 보겠습니다.

**Comment by corazzon** [comment]
[kernel360.github.io](https://kernel360.github.io/) 다음의 주소에서 블로그로 리다이렉트 되도록 하였습니다.
